const ACTION_TYPES = {
  SET_PODCASTS: "SET_PODCASTS",
  SET_PODCAST_EPISODES: "SET_PODCAST_EPISODES",
  SET_IS_LOADING: "SET_IS_LOADING",
  SET_IS_FIRST_START: "SET_IS_FIRST_START",
  SET_LAST_PODCASTS_UPDATED_DATE: "SET_LAST_PODCASTS_UPDATED_DATE",
  SET_LAST_PODCAST_EPISODES_UPDATED_DATE: "SET_LAST_PODCAST_EPISODES_UPDATED_DATE",
  RESET: "RESET",
};

export default ACTION_TYPES;
