const ACTION_TYPES = {
  SET_PODCASTS: "SET_PODCASTS",
  SET_PODCAST: "SET_PODCAST",
  SET_IS_LOADING: "SET_IS_LOADING",
  SET_IS_FIRST_START: "SET_IS_FIRST_START",
  SET_LAST_PODCASTS_UPDATED_DATE: "SET_LAST_PODCASTS_UPDATED_DATE",
  SET_LAST_DETAIL_PODCAST_UPDATED_DATE: "SET_LAST_DETAIL_PODCAST_UPDATED_DATE",
  RESET: "RESET",
};

export default ACTION_TYPES;
